Vagrant.configure "2" do |config|

  config.vm.box = "vagrant-hackaton"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.cache.auto_detect = true

  config.vm.network :forwarded_port, guest: 80, host: 8081

  config.vm.synced_folder "webapp/", "/var/www/html", nfs: true

end