require 'rbconfig'
is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)

Vagrant.configure "2" do |config|

  config.vm.box = "vagrant-hackaton"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.cache.auto_detect = true

  config.vm.synced_folder "webapp/", "/var/www/html", nfs: true

  (1..3).each do |i|
    config.vm.define "slave-#{i}" do |slave|
  
      slave.vm.network :forwarded_port, guest: 80, host: 8080 + i
      slave.vm.provision "shell",
        inline: "echo hello from slave #{i}"
    end
  end

end